# Generated by Django 6.0.5 on 2026-05-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comune', models.CharField(max_length=150)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('foglio', models.CharField(blank=True, max_length=50)),
                ('mappale', models.CharField(blank=True, max_length=50)),
                ('subalterno', models.CharField(blank=True, max_length=50)),
                ('categoria_catastale', models.CharField(blank=True, max_length=50)),
                ('zona_urbanistica', models.CharField(blank=True, max_length=100)),
                ('vincoli', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienti.cliente')),
            ],
        ),
    ]
