# Generated by Django 6.0.5 on 2026-05-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('immobili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pratica', models.CharField(choices=[('CILA', 'CILA'), ('SCIA', 'SCIA'), ('PDC', 'Permesso di Costruire'), ('SANATORIA', 'Sanatoria'), ('PAESAGGISTICA', 'Paesaggistica'), ('CATASTO', 'Catasto'), ('FRAZIONAMENTO', 'Frazionamento'), ('SUCCESSIONE', 'Successione'), ('APE', 'APE'), ('PERIZIA', 'Perizia')], max_length=50)),
                ('stato', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('IN_CORSO', 'In corso'), ('DEPOSITATA', 'Depositata'), ('INTEGRAZIONE', 'Integrazione'), ('APPROVATA', 'Approvata'), ('CONCLUSA', 'Conclusa')], default='IN_CORSO', max_length=50)),
                ('oggetto', models.CharField(max_length=255)),
                ('comune', models.CharField(max_length=150)),
                ('protocollo', models.CharField(blank=True, max_length=100)),
                ('data_incarico', models.DateField(blank=True, null=True)),
                ('data_deposito', models.DateField(blank=True, null=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('compenso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienti.cliente')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobili.immobile')),
            ],
        ),
    ]
