# Generated by Django 6.0.5 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='stato',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('IN CORSO', 'In corso'), ('DEPOSITATA', 'Depositata'), ('INTEGRAZIONE', 'Integrazione'), ('APPROVATA', 'Approvata'), ('CONCLUSA', 'Conclusa')], default='IN_CORSO', max_length=50),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='tipo_pratica',
            field=models.CharField(max_length=255),
        ),
    ]
