# Generated by Django 6.0.5 on 2026-05-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0002_alter_pratica_stato_alter_pratica_tipo_pratica'),
        ('studi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratica',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pratiche', to='studi.studio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pratica',
            name='stato',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('IN_CORSO', 'In corso'), ('DEPOSITATA', 'Depositata'), ('INTEGRAZIONE', 'Integrazione'), ('APPROVATA', 'Approvata'), ('CONCLUSA', 'Conclusa')], default='IN_CORSO', max_length=50),
        ),
    ]
