# Generated by Django 6.0.5 on 2026-05-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('pratiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('APPUNTAMENTO', 'Appuntamento'), ('SOPRALLUOGO', 'Sopralluogo'), ('SCADENZA', 'Scadenza'), ('TELEFONATA', 'Telefonata'), ('RIUNIONE', 'Riunione'), ('ALTRO', 'Altro')], default='APPUNTAMENTO', max_length=30)),
                ('priorita', models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('completato', models.BooleanField(default=False)),
                ('descrizione', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clienti.cliente')),
                ('pratica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.pratica')),
            ],
        ),
    ]
