# Generated by Django 6.0.5 on 2026-05-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('studi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventi_agenda', to='studi.studio'),
            preserve_default=False,
        ),
    ]
