# Generated by Django 6.0.5 on 2026-06-18 07:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pratiche', '0003_pratica_studio_alter_pratica_stato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceOra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo_attivita', models.CharField(choices=[('SOPRALLUOGO', 'Sopralluogo'), ('RILIEVO', 'Rilievo'), ('PROGETTAZIONE', 'Progettazione'), ('DISEGNO', 'Disegno / elaborati grafici'), ('PRATICA', 'Gestione pratica'), ('INCONTRO', 'Incontro / riunione'), ('TELEFONATA', 'Telefonata / email'), ('ISTRUTTORIA', 'Istruttoria / verifica documentale'), ('CATASTO', 'Catasto'), ('DIREZIONE_LAVORI', 'Direzione lavori'), ('SICUREZZA', 'Sicurezza'), ('ALTRO', 'Altro')], default='ALTRO', max_length=30)),
                ('descrizione', models.TextField(blank=True)),
                ('ore', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('tariffa_oraria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fatturabile', models.BooleanField(default=True)),
                ('inserita_in_parcella', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_ore', to='pratiche.pratica')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_ore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voce ore',
                'verbose_name_plural': 'Voci ore',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
