# Generated by Django 6.0.5 on 2026-05-07 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREAZIONE', 'Creazione'), ('MODIFICA', 'Modifica'), ('ELIMINAZIONE', 'Eliminazione'), ('UPLOAD', 'Upload documento'), ('PDF', 'Generazione PDF'), ('ALTRO', 'Altro')], default='ALTRO', max_length=30)),
                ('descrizione', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
