# Generated by Django 6.0.5 on 2026-05-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0001_initial'),
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='pratica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='pratiche.pratica'),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='tipo',
            field=models.CharField(choices=[('CREAZIONE', 'Creazione'), ('MODIFICA', 'Modifica'), ('ELIMINAZIONE', 'Eliminazione'), ('UPLOAD', 'Upload documento'), ('PDF', 'Generazione PDF'), ('SCADENZA', 'Scadenza'), ('PARCELLA', 'Parcella'), ('ALTRO', 'Altro')], default='ALTRO', max_length=30),
        ),
    ]
