# Generated by Django 6.0.5 on 2026-05-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('TAVOLA', 'Tavola grafica'), ('RELAZIONE', 'Relazione tecnica'), ('MODELLO', 'Modello pratica'), ('RICEVUTA', 'Ricevuta / Protocollo'), ('FOTO', 'Foto'), ('PEC', 'PEC'), ('ALTRO', 'Altro')], default='ALTRO', max_length=50)),
                ('file', models.FileField(upload_to='documenti_pratiche/')),
                ('note', models.TextField(blank=True)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='pratiche.pratica')),
            ],
        ),
    ]
