# Generated by Django 6.0.5 on 2026-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='abbonamento_scade_il',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='aggiornato_il',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='limite_pratiche',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='studio',
            name='limite_storage_mb',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='studio',
            name='limite_utenti',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studio',
            name='piano',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='studio',
            name='stato_abbonamento',
            field=models.CharField(choices=[('ATTIVO', 'Attivo'), ('TRIAL', 'Trial'), ('SCADUTO', 'Scaduto'), ('ANNULLATO', 'Annullato')], default='TRIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='studio',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studio',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studio',
            name='trial_fino_al',
            field=models.DateField(blank=True, null=True),
        ),
    ]
