# Generated by Django 6.0.5 on 2026-07-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studi', '0002_studio_abbonamento_scade_il_studio_aggiornato_il_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='calendario_ics_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
