# Generated by Django 6.0.5 on 2026-05-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EDILIZIA_UNIPASS', 'Edilizia / UNIPASS'), ('CATASTO', 'Catasto'), ('ENERGIA', 'Energia'), ('SUCCESSIONI_STIME', 'Successioni e stime'), ('STRUTTURE', 'Strutture / Genio Civile'), ('AMBIENTE', 'Ambiente / VINCA / Scarichi'), ('SICUREZZA_CANTIERI', 'Sicurezza cantieri'), ('CONTABILITA', 'Computi / Contabilità lavori'), ('ALTRO', 'Altro')], max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaseWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('giorni_scadenza', models.PositiveIntegerField(blank=True, help_text='Giorni dopo la creazione pratica', null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi', to='workflow.tipoworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voce', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='workflow.tipoworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_attivazione', models.DateField(auto_now_add=True)),
                ('completato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('pratica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_pratica', to='pratiche.pratica')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.tipoworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='FasePratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('completata', models.BooleanField(default=False)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('workflow_pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi_pratica', to='workflow.workflowpratica')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voce', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('completato', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('workflow_pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_pratica', to='workflow.workflowpratica')),
            ],
        ),
    ]
