# Generated by Django 6.0.5 on 2026-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoworkflow',
            name='categoria',
            field=models.CharField(choices=[('EDILIZIA', 'Edilizia'), ('CATASTO', 'Catasto'), ('ENERGIA', 'Energia'), ('SUCCESSIONI_STIME', 'Successioni e stime'), ('STRUTTURE', 'Strutture / Genio Civile'), ('AMBIENTE', 'Ambiente / VINCA / Scarichi'), ('SICUREZZA_CANTIERI', 'Sicurezza cantieri'), ('CONTABILITA', 'Computi / Contabilità lavori'), ('ALTRO', 'Altro')], max_length=50),
        ),
    ]
