# Generated by Django 6.0.5 on 2026-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_tipoworkflow_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoworkflow',
            name='categoria',
            field=models.CharField(choices=[('EDILIZIA', 'Edilizia'), ('CATASTO', 'Catasto'), ('ENERGIA', 'Energia'), ('PRATICHE_IMMOBILIARI_NOTARILI', 'Pratiche immobiliari e notarili'), ('STRUTTURE', 'Strutture'), ('AMBIENTE', 'Ambiente'), ('SICUREZZA_CANTIERI', 'Sicurezza cantieri'), ('CONTABILITA', 'Contabilità'), ('ALTRO', 'Altro')], max_length=50),
        ),
    ]
