# Generated by Django 6.0.5 on 2026-05-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_emissione', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('DA_PAGARE', 'Da pagare'), ('PARZIALE', 'Parziale'), ('PAGATO', 'Pagato')], default='DA_PAGARE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='pratiche.pratica')),
            ],
        ),
    ]
