# Generated by Django 6.0.5 on 2026-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcella',
            name='data_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcella',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=5),
        ),
        migrations.AddField(
            model_name='parcella',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parcella',
            name='tipo_documento',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('PARCELLA', 'Parcella'), ('FATTURA', 'Fattura')], default='PARCELLA', max_length=20),
        ),
    ]
