# Generated by Django 6.0.5 on 2026-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0002_parcella_data_scadenza_parcella_iva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcella',
            options={'ordering': ['-data_emissione', '-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='parcella',
            name='aliquota_cassa',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='parcella',
            name='applica_bollo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcella',
            name='applica_cassa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parcella',
            name='applica_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parcella',
            name='importo_bollo',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='parcella',
            name='tipo_cassa',
            field=models.CharField(choices=[('NESSUNA', 'Nessuna cassa'), ('GEOMETRI', 'Geometri / Cassa Geometri'), ('INARCASSA', 'Architetti-Ingegneri / Inarcassa'), ('EPPI', 'Periti Industriali / EPPI'), ('MANUALE', 'Altro / Manuale')], default='GEOMETRI', max_length=30),
        ),
    ]
