# Generated by Django 6.0.5 on 2026-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('partita_iva', models.CharField(blank=True, max_length=20)),
                ('indirizzo', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
